### ISSUE TITLE
Relying on GPUJPEG is probably a mistake

### ISSUE THREAD

**Issue by xlz** [yoshimoto/libk4w2#1]
Hi, first thank you for your Kinect2 kernel driver!

I also tried integrated GPUJPEG for accelerating JPEG decoding, but it proves to be ineffective. Reasons:

* GPUJPEG's performance will not be much better than TurboJPEG.
* GPUJPEG's performance does not scale with GPU performance: the hard part is Huffman decoding which can only be processed sequentially. I have also tried parallelizing it using JPEG restart intervals (about 300(?) parallel threads on GPU doing Huffman decoding), and it showed minimum improvement.
* GPUJPEG reduces CUDA depth processing performance by competing for GPU compute resources and bus bandwidth.
* GPUJPEG is significantly less well tested than TurboJPEG.

**Comment by yoshimoto** [comment]
Thank you for comment!

First of all, my GPUJPEG-based decoder works faster than TurboJPEG's one in my environment.
In addition,  libk4w2 supports both TurboJPEG and GPUJPEG.
You can easily select the best one for your purpose :-)

In more detail, libk4w2 has a flag to disable GPUJPEG, named K4W2_DECODER_DISABLE_CUDA.
If libk4w2 was built with both turbojpeg and gpujpeg, then
k4w2_decoder_open(K4W2_DECODER_COLOR) returns GPUJPEG's decoder , and
k4w2_decoder_open(K4W2_DECODER_COLOR + K4W2_DECODER_DISABLE_CUDA)
returns TurboJPEG's.
Please see the following source codes for details;
- include/libk4w2/decoder.h    --  definition of public API
- src/modules.h   --  private header file for decoder module
- src/decoder.c  
- src/decoder_cuda/color_cuda.c   --  implementation of GPUJPEG-based decoder

Also, I've modified GPUJPEG's API to improve the utilization ratio
of resources, such as bus bandwidth and GPU's cores. The patch is available at 
https://sourceforge.net/u/yosimoto/gpujpeg/ci/7821bcebe924845a21dec95885bc62c67b36e8d1/
This patch devides gpujpeg_decoder_decode() into two parts;
gpujpeg_decoder_request() to enqueue the decoding task to the GPU, and
gpujpeg_decoder_fetch() to wait for the result.
(Please note that the current version of libk4w2 requires this modified version of GPUJPEG.)

I have no time to validate this modification in detail. However, it seems to work well.
The benchmark results are as follows.
90fps when using GPUJPEG + OpenCL-based depth decoder
66fps when using Turbojpeg + OpenCL-based depth decoder
50fps when using GPUJPEG + CPU-based depth decoder
41fps when using Turbojpeg + CPU-based depth decoder
(I use GTX 980 and i7-5820K@3.3GHz now)

**Comment by yoshimoto** [comment]
I've commited new sample code; example/opengl.c. 

It uses CUDA-OpenGL and OpenCL-OpenGL interoperabilities so it runs at 30FPS with utilizing 35% of single CPU's core and 33% of GPU.

If you are interested, please try it.
