### ISSUE TITLE
opengl.c build errors

### ISSUE THREAD

**Issue by ProgmasterX** [yoshimoto/libk4w2#10]
progmaster@Microsoft:~/Kinect/libk4w2/build$ make
[ 77%] Built target k4w2
Linking CXX executable ../bin/liveview
[ 83%] Built target liveview
Scanning dependencies of target opencv
[ 88%] Building CXX object examples/CMakeFiles/opencv.dir/opencv.cpp.o
Linking CXX executable ../bin/opencv
[ 88%] Built target opencv
Scanning dependencies of target opengl
[ 94%] Building C object examples/CMakeFiles/opengl.dir/opengl.c.o
/home/progmaster/Kinect/libk4w2/examples/opengl.c: In function ‘create_opengl_window’:
/home/progmaster/Kinect/libk4w2/examples/opengl.c:68:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int retry = 0; retry<10; ++retry) {
     ^
/home/progmaster/Kinect/libk4w2/examples/opengl.c:68:5: note: use option -std=c99 or -std=gnu99 to compile your code
/home/progmaster/Kinect/libk4w2/examples/opengl.c: In function ‘create_glsl_program’:
/home/progmaster/Kinect/libk4w2/examples/opengl.c:148:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i=0; i<2; ++i) {
     ^
/home/progmaster/Kinect/libk4w2/examples/opengl.c: In function ‘main’:
/home/progmaster/Kinect/libk4w2/examples/opengl.c:228:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < 2; ++i) {
     ^
/home/progmaster/Kinect/libk4w2/examples/opengl.c:266:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (size_t i=0; i<2; ++i) {
  ^
/home/progmaster/Kinect/libk4w2/examples/opengl.c:296:17: error: redefinition of ‘i’
     for (size_t i = 0; i < 2; ++i) {
                 ^
/home/progmaster/Kinect/libk4w2/examples/opengl.c:228:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < 2; ++i) {
                 ^
/home/progmaster/Kinect/libk4w2/examples/opengl.c:296:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < 2; ++i) {
     ^
make[2]: *** [examples/CMakeFiles/opengl.dir/opengl.c.o] Error 1
make[1]: *** [examples/CMakeFiles/opengl.dir/all] Error 2
make: *** [all] Error 2

But if I fix these errors, a linker error occurs
Linking C executable ../bin/opengl
/usr/bin/ld: /usr/local/lib/libglfw3.a(posix_tls.c.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opengl] Error 1
make[1]: *** [examples/CMakeFiles/opengl.dir/all] Error 2
make: *** [all] Error 2

**Comment by yoshimoto** [comment]
Thank you for you reports.
I've fixed this issue.
