### ISSUE TITLE
Undefined reference to gpujpeg

### ISSUE THREAD

**Issue by ProgmasterX** [yoshimoto/libk4w2#5]
[ 86%] Built target k4w2
Scanning dependencies of target liveview
[ 93%] Building CXX object examples/CMakeFiles/liveview.dir/liveview.cpp.o
Linking CXX executable ../bin/liveview
../lib/libk4w2.so.0.0.0: undefined reference to `gpujpeg_decoder_fetch'
../lib/libk4w2.so.0.0.0: undefined reference to `gpujpeg_decoder_request'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/liveview.dir/build.make:108: recipe for target 'bin/liveview' failed
make[2]: *** [bin/liveview] Error 1
CMakeFiles/Makefile2:127: recipe for target 'examples/CMakeFiles/liveview.dir/all' failed
make[1]: *** [examples/CMakeFiles/liveview.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yoshimoto** [comment]
Thank you for your report.

libk4w2 needs a "modified version" of gpujpeg, which is 
avaiable at git://git.code.sf.net/u/yosimoto/gpujpeg.

See https://github.com/yoshimoto/libk4w2/issues/3 for details.

**Comment by ProgmasterX** [comment]
I downloaded modified version, but compiling it gives me another error
progmaster@Monster:~/Kinect$ git clone git://git.code.sf.net/u/yosimoto/gpujpeg
Cloning into 'gpujpeg'...
remote: Counting objects: 2327, done.
remote: Compressing objects: 100% (1388/1388), done.
remote: Total 2327 (delta 1789), reused 1214 (delta 930)
Receiving objects: 100% (2327/2327), 6.66 MiB | 769.00 KiB/s, done.
Resolving deltas: 100% (1789/1789), done.
Checking connectivity... done.
progmaster@Monster:~/Kinect$ cd gpujpeg
progmaster@Monster:~/Kinect/gpujpeg$ ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:21: installing './compile'
configure.ac:21: installing './config.guess'
configure.ac:21: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am:86: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:89: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:93: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:97: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './depcomp'
test/memcheck/Makefile.am:10: warning: deprecated feature: target 'memcheck' overrides 'memcheck$(EXEEXT)'
test/memcheck/Makefile.am:10: change your target to read 'memcheck$(EXEEXT)'
/usr/share/automake-1.14/am/program.am: target 'memcheck$(EXEEXT)' was defined here
test/memcheck/Makefile.am:5:   while processing program 'memcheck'
test/memcheck/Makefile.am:20: warning: deprecated feature: target 'memcheck_cuda.sh' overrides 'memcheck_cuda.sh$(EXEEXT)'
test/memcheck/Makefile.am:20: change your target to read 'memcheck_cuda.sh$(EXEEXT)'
/usr/share/automake-1.14/am/program.am: target 'memcheck_cuda.sh$(EXEEXT)' was defined here
test/memcheck/Makefile.am:4:   while processing program 'memcheck_cuda.sh'
test/memcheck/Makefile.am:13: warning: deprecated feature: target 'memcheck_local.sh' overrides 'memcheck_local.sh$(EXEEXT)'
test/memcheck/Makefile.am:13: change your target to read 'memcheck_local.sh$(EXEEXT)'
/usr/share/automake-1.14/am/program.am: target 'memcheck_local.sh$(EXEEXT)' was defined here
test/memcheck/Makefile.am:4:   while processing program 'memcheck_local.sh'
parallel-tests: installing './test-driver'
test/opengl_interop/Makefile.am:28: warning: '%'-style pattern rules are a GNU make extension
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for nvcc... /usr/local/cuda-7.5/bin/nvcc
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libgpujpeg.pc
config.status: creating test/memcheck/Makefile
config.status: creating test/opengl_interop/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Configuration summary:

  Target ...................... x86_64-unknown-linux-gnu
  Prefix ...................... /usr/local
  Debug ....................... 

  Constant tables.............. yes
  OpenGL ...................... no

  CUDA root ................... /usr/local/cuda-7.5



Autogen done.
progmaster@Monster:~/Kinect/gpujpeg$ make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/progmaster/Kinect/gpujpeg/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
make  all-recursive
make[1]: Entering directory '/home/progmaster/Kinect/gpujpeg'
Making all in .
make[2]: Entering directory '/home/progmaster/Kinect/gpujpeg'
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.    -fPIC  -O2 -I. -I/usr/local/cuda-7.5/include -g -O2 -MT src/libgpujpeg_la-gpujpeg_common.lo -MD -MP -MF src/.deps/libgpujpeg_la-gpujpeg_common.Tpo -c -o src/libgpujpeg_la-gpujpeg_common.lo `test -f 'src/gpujpeg_common.cpp' || echo './'`src/gpujpeg_common.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -fPIC -O2 -I. -I/usr/local/cuda-7.5/include -g -O2 -MT src/libgpujpeg_la-gpujpeg_common.lo -MD -MP -MF src/.deps/libgpujpeg_la-gpujpeg_common.Tpo -c src/gpujpeg_common.cpp  -fPIC -DPIC -o src/.libs/libgpujpeg_la-gpujpeg_common.o
src/gpujpeg_common.cpp: In function 'int gpujpeg_coder_init(gpujpeg_coder*)':
src/gpujpeg_common.cpp:536:18: warning: zero-length gnu_printf format string [-Wformat-zero-length]
         printf("");
                  ^
src/gpujpeg_common.cpp: In function 'int gpujpeg_opengl_texture_create(int, int, uint8_t*)':
src/gpujpeg_common.cpp:948:5: error: 'GLuint' was not declared in this scope
     GLuint texture_id = 0;
     ^
src/gpujpeg_common.cpp:965:12: error: 'texture_id' was not declared in this scope
     return texture_id;
            ^
Makefile:732: recipe for target 'src/libgpujpeg_la-gpujpeg_common.lo' failed
make[2]: *** [src/libgpujpeg_la-gpujpeg_common.lo] Error 1
make[2]: Leaving directory '/home/progmaster/Kinect/gpujpeg'
Makefile:874: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/progmaster/Kinect/gpujpeg'
Makefile:477: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ProgmasterX** [comment]
I fixed that by ./configure --enable-opengl

**Comment by ProgmasterX** [comment]
Fixed! Added /usr/local/lib to LD_LIBRARY_PATH and
[ 86%] Built target k4w2
Linking CXX executable ../bin/liveview
[ 93%] Built target liveview
Scanning dependencies of target simple
[100%] Building C object examples/CMakeFiles/simple.dir/simple.c.o
Linking C executable ../bin/simple
[100%] Built target simple
