### ISSUE TITLE
No depth

### ISSUE THREAD

**Issue by ProgmasterX** [yoshimoto/libk4w2#7]
When I run sudo ./liveview only color frames are received, but not depth
If I install gspca-kinect2 and then run sudo ./liveview the depth and IR frames are received but they are empty

My specifications:
CPU Intel Core i5-2500K
Motherboard Asus P8Z77-M
Intel USB3.0 Controller
GPU NVIDIA GT 640
SSD OCZ Vertex 3
OS Ubuntu 15.04

And, when running sudo ./liveview the Xbox LED on the Kinect sensor is not on, but red IR emitter is on.
![screenshot from 2015-10-19 12 30 26](https://cloud.githubusercontent.com/assets/15179640/10572063/2d3790b8-765e-11e5-9fc6-384b55e547d1.png)
![dsc04479](https://cloud.githubusercontent.com/assets/15179640/10572070/3dc8b204-765e-11e5-9014-2d1679c0ef60.JPG)

**Comment by yoshimoto** [comment]
I think your trouble is that depth decoder or its visualizer is not working.
Have you tried examples/opengl?

**Comment by ProgmasterX** [comment]
In build/bin I have only liveview and simple, but no opengl
But I see examples/opengl.c, how do I compile it?

**Comment by yoshimoto** [comment]
Oops, I forget to update CMakefiles for example/opengl.c.

Anyway,  could you try the following instructions?

First, install glfw library.
$ sudo apt-get install libglfw3-dev

Then comple and run opengl.c
$ cd examples
$ make 
$ ./opengl

**Comment by ProgmasterX** [comment]
progmaster@Monster:~/Kinect/libk4w2/examples$ make
cc  `pkg-config libk4w2 --cflags` `pkg-config glfw3 glew --cflags` `pkg-config libk4w2 --libs`  simple.c  `pkg-config glfw3 glew --libs` -o simple
/tmp/cc9vsnVp.o: In function `main':
simple.c:(.text+0xbb): undefined reference to `k4w2_open'
simple.c:(.text+0x106): undefined reference to `k4w2_set_depth_callback'
simple.c:(.text+0x112): undefined reference to `k4w2_start'
simple.c:(.text+0x13f): undefined reference to `k4w2_stop'
simple.c:(.text+0x14b): undefined reference to `k4w2_close'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'simple' failed
make: *** [simple] Error 1

**Comment by yoshimoto** [comment]
It seems to be pkg-config issue.

I think you need
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
or
export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig

**Comment by ProgmasterX** [comment]
Tried, the same error
progmaster@Monster:~/Kinect/libk4w2/examples$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
progmaster@Monster:~/Kinect/libk4w2/examples$ make
cc  `pkg-config libk4w2 --cflags` `pkg-config glfw3 glew --cflags` `pkg-config libk4w2 --libs`  simple.c  `pkg-config glfw3 glew --libs` -o simple
/tmp/cc4WVFIu.o: In function `main':
simple.c:(.text+0xbb): undefined reference to `k4w2_open'
simple.c:(.text+0x106): undefined reference to `k4w2_set_depth_callback'
simple.c:(.text+0x112): undefined reference to `k4w2_start'
simple.c:(.text+0x13f): undefined reference to `k4w2_stop'
simple.c:(.text+0x14b): undefined reference to `k4w2_close'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'simple' failed
make: *** [simple] Error 1
progmaster@Monster:~/Kinect/libk4w2/examples$

**Comment by yoshimoto** [comment]
Try this;
$ gcc `pkg-config glfw3 glew libk4w2 opencv --cflags --libs` opengl.c -o opengl

**Comment by ProgmasterX** [comment]
progmaster@Monster:~/Kinect/libk4w2/examples$ gcc pkg-config glfw3 glew libk4w2 opencv --cflags --libs opengl.c -o opengl
gcc: error: pkg-config: No such file or directory
gcc: error: glfw3: No such file or directory
gcc: error: glew: No such file or directory
gcc: error: libk4w2: No such file or directory
gcc: error: opencv: No such file or directory
gcc: error: unrecognized command line option ‘--cflags’
gcc: error: unrecognized command line option ‘--libs’

**Comment by ProgmasterX** [comment]
With quotes
progmaster@Monster:~/Kinect/libk4w2/examples$ gcc `pkg-config glfw3 glew libk4w2 opencv --cflags --libs` opengl.c -o opengl
/tmp/ccsAaYvP.o: In function `key_callback':
opengl.c:(.text+0x3a): undefined reference to `glfwSetWindowShouldClose'
/tmp/ccsAaYvP.o: In function `create_opengl_window':
opengl.c:(.text+0x54): undefined reference to `glfwInit'
opengl.c:(.text+0x63): undefined reference to `glfwWindowHint'
opengl.c:(.text+0x72): undefined reference to `glfwWindowHint'
opengl.c:(.text+0x81): undefined reference to `glfwWindowHint'
opengl.c:(.text+0x90): undefined reference to `glfwWindowHint'
opengl.c:(.text+0xac): undefined reference to `glfwCreateWindow'
opengl.c:(.text+0xbc): undefined reference to `glfwTerminate'
opengl.c:(.text+0xd7): undefined reference to `glfwSetKeyCallback'
opengl.c:(.text+0xe3): undefined reference to `glfwMakeContextCurrent'
opengl.c:(.text+0xe9): undefined reference to `glewExperimental'
opengl.c:(.text+0xef): undefined reference to `glewInit'
opengl.c:(.text+0x104): undefined reference to `glGetError'
opengl.c:(.text+0x11e): undefined reference to `glGetString'
opengl.c:(.text+0x14c): undefined reference to `glGetString'
/tmp/ccsAaYvP.o: In function `color_cb':
opengl.c:(.text+0x1e4): undefined reference to `glfwPostEmptyEvent'
/tmp/ccsAaYvP.o: In function `depth_cb':
opengl.c:(.text+0x24e): undefined reference to `glfwPostEmptyEvent'
/tmp/ccsAaYvP.o: In function `create_glsl_program':
opengl.c:(.text+0x26e): undefined reference to `__glewCreateProgram'
opengl.c:(.text+0x28f): undefined reference to `__glewCreateShader'
opengl.c:(.text+0x2a8): undefined reference to `__glewShaderSource'
opengl.c:(.text+0x2cd): undefined reference to `__glewCompileShader'
opengl.c:(.text+0x2db): undefined reference to `__glewGetShaderiv'
opengl.c:(.text+0x31c): undefined reference to `__glewGetShaderiv'
opengl.c:(.text+0x34c): undefined reference to `__glewGetShaderInfoLog'
opengl.c:(.text+0x394): undefined reference to `__glewAttachShader'
opengl.c:(.text+0x3a7): undefined reference to `__glewDeleteShader'
opengl.c:(.text+0x3ba): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x3e6): undefined reference to `glGetError'
opengl.c:(.text+0x406): undefined reference to `__glewLinkProgram'
opengl.c:(.text+0x419): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x445): undefined reference to `glGetError'
/tmp/ccsAaYvP.o: In function `main':
opengl.c:(.text+0x48b): undefined reference to `k4w2_set_debug_level'
opengl.c:(.text+0x4b5): undefined reference to `k4w2_open'
opengl.c:(.text+0x52a): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x559): undefined reference to `glGetError'
opengl.c:(.text+0x583): undefined reference to `k4w2_decoder_open'
opengl.c:(.text+0x599): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x5c8): undefined reference to `glGetError'
opengl.c:(.text+0x5ef): undefined reference to `k4w2_decoder_open'
opengl.c:(.text+0x605): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x634): undefined reference to `glGetError'
opengl.c:(.text+0x65c): undefined reference to `k4w2_read_color_camera_param'
opengl.c:(.text+0x6aa): undefined reference to `k4w2_read_depth_camera_param'
opengl.c:(.text+0x6f8): undefined reference to `k4w2_read_p0table'
opengl.c:(.text+0x751): undefined reference to `k4w2_decoder_set_params'
opengl.c:(.text+0x7a1): undefined reference to `k4w2_set_color_callback'
opengl.c:(.text+0x7bc): undefined reference to `k4w2_set_depth_callback'
opengl.c:(.text+0x7cb): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x7fa): undefined reference to `glGetError'
opengl.c:(.text+0x868): undefined reference to `k4w2_decoder_get_gl_texture'
opengl.c:(.text+0x8ba): undefined reference to `__glewGenVertexArrays'
opengl.c:(.text+0x8d2): undefined reference to `__glewBindVertexArray'
opengl.c:(.text+0x8eb): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x91a): undefined reference to `glGetError'
opengl.c:(.text+0x940): undefined reference to `__glewUseProgram'
opengl.c:(.text+0x959): undefined reference to `glewGetErrorString'
opengl.c:(.text+0x988): undefined reference to `glGetError'
opengl.c:(.text+0x99e): undefined reference to `__glewActiveTexture'
opengl.c:(.text+0x9b7): undefined reference to `glBindTexture'
opengl.c:(.text+0x9be): undefined reference to `__glewGetUniformLocation'
opengl.c:(.text+0x9e3): undefined reference to `__glewUniform1i'
opengl.c:(.text+0xa01): undefined reference to `glewGetErrorString'
opengl.c:(.text+0xa30): undefined reference to `glGetError'
opengl.c:(.text+0xa46): undefined reference to `__glewActiveTexture'
opengl.c:(.text+0xa5f): undefined reference to `glBindTexture'
opengl.c:(.text+0xa66): undefined reference to `__glewGetUniformLocation'
opengl.c:(.text+0xa8b): undefined reference to `__glewUniform1i'
opengl.c:(.text+0xaa1): undefined reference to `__glewActiveTexture'
opengl.c:(.text+0xab7): undefined reference to `glewGetErrorString'
opengl.c:(.text+0xae6): undefined reference to `glGetError'
opengl.c:(.text+0xb04): undefined reference to `k4w2_start'
opengl.c:(.text+0xb40): undefined reference to `__glewUseProgram'
opengl.c:(.text+0xbc3): undefined reference to `k4w2_decoder_request'
opengl.c:(.text+0xbd8): undefined reference to `glewGetErrorString'
opengl.c:(.text+0xc07): undefined reference to `glGetError'
opengl.c:(.text+0xc6d): undefined reference to `__glewUseProgram'
opengl.c:(.text+0xc86): undefined reference to `glewGetErrorString'
opengl.c:(.text+0xcb5): undefined reference to `glGetError'
opengl.c:(.text+0xcd8): undefined reference to `glDrawArrays'
opengl.c:(.text+0xce7): undefined reference to `glewGetErrorString'
opengl.c:(.text+0xd16): undefined reference to `glGetError'
opengl.c:(.text+0xd2c): undefined reference to `__glewUseProgram'
opengl.c:(.text+0xd42): undefined reference to `glfwSwapBuffers'
opengl.c:(.text+0xd47): undefined reference to `glfwWaitEvents'
opengl.c:(.text+0xd56): undefined reference to `glfwWindowShouldClose'
opengl.c:(.text+0xd6d): undefined reference to `k4w2_stop'
opengl.c:(.text+0xd97): undefined reference to `k4w2_decoder_close'
opengl.c:(.text+0xdb8): undefined reference to `k4w2_close'
opengl.c:(.text+0xdbd): undefined reference to `glfwTerminate'
collect2: error: ld returned 1 exit status

**Comment by yoshimoto** [comment]
How about this?
```bash
$ gcc  -o opengl opengl.c `pkg-config glfw3 glew libk4w2 opencv --cflags --libs`
```

**Comment by ProgmasterX** [comment]
progmaster@Monster:~/Kinect/libk4w2/examples$ gcc  -o opengl opengl.c `pkg-config glfw3 glew libk4w2 opencv --cflags --libs`
/tmp/ccrUKamP.o: In function `color_cb':
opengl.c:(.text+0x1e4): undefined reference to `glfwPostEmptyEvent'
/tmp/ccrUKamP.o: In function `depth_cb':
opengl.c:(.text+0x24e): undefined reference to `glfwPostEmptyEvent'
collect2: error: ld returned 1 exit status

**Comment by yoshimoto** [comment]
Your glfw3 seems to be older than I used. I've tested only with glfw3 3.1.2.

Could you try to edit opengl.c manually as follows:
* Comment-out glfwPostEmptyEvent(). there are two lines in opengl.c
* Replace glfwWaitEvents(); with glfwPollEvents();

This is just a workaround for older glfw3. however, I wish it could work ;-)

**Comment by ProgmasterX** [comment]
Edited
progmaster@Monster:~/Kinect/libk4w2/examples$ gcc  -o opengl opengl.c `pkg-config glfw3 glew libk4w2 opencv --cflags --libs`
progmaster@Monster:~/Kinect/libk4w2/examples$ ./opengl
opengl.c:63 render:  GeForce GT 640/PCIe/SSE2
opengl.c:64 version: 4.1.0 NVIDIA 352.39
/home/progmaster/Kinect/libk4w2/src/driver_v4l2.c:50 Cannot identify '/dev/video0'; No such file or directory
/home/progmaster/Kinect/libk4w2/src/driver_v4l2.c:268 open_camera(/dev/video0) failed
/home/progmaster/Kinect/libk4w2/src/driver_libusb/driver_libusb.c:501 libusb_init(&usb->context)
/home/progmaster/Kinect/libk4w2/src/driver_libusb/driver_libusb.c:502 open_device(usb, device_id, attempt_reset)
/home/progmaster/Kinect/libk4w2/src/driver_libusb/driver_libusb.c:204 libusb_open(usb->dev, &usb->handle)
/home/progmaster/Kinect/libk4w2/src/driver_libusb/driver_libusb.c:204 libusb_open(usb->dev, &usb->handle) returns LIBUSB_ERROR_ACCESS
/home/progmaster/Kinect/libk4w2/src/driver_libusb/driver_libusb.c:502 open_device(usb, device_id, attempt_reset) returns LIBUSB_ERROR_NOT_FOUND
/home/progmaster/Kinect/libk4w2/src/driver_libusb/driver_libusb.c:628 k4w2_libusb_close
opengl.c:175 failed to open kinect device.
progmaster@Monster:~/Kinect/libk4w2/examples$ sudo ./opengl
[sudo] password for progmaster: 
./opengl: error while loading shared libraries: libk4w2.so.0.0.0: cannot open shared object file: No such file or directory

**Comment by ProgmasterX** [comment]
$ sudo ln /usr/local/lib/libk4w2.so.0.0.0 /usr/lib/libk4w2.so.0.0.0
$ sudo ./opengl

But still no depth
![screenshot from 2015-10-19 15 06 35](https://cloud.githubusercontent.com/assets/15179640/10575007/0cc9f856-7673-11e5-9426-ecaceaa5f7f8.png)

**Comment by ProgmasterX** [comment]
Rebooted and it worked. Thanks.
![screenshot from 2015-10-19 15 18 21](https://cloud.githubusercontent.com/assets/15179640/10575318/fde81e60-7674-11e5-9f2e-a18676a7bb13.png)

**Comment by yoshimoto** [comment]
I've updated some files so that the opengl-based example is compiled automatically.
Thank you for your reports.
