### ISSUE TITLE
OpenCL undefined reference

### ISSUE THREAD

**Issue by ProgmasterX** [yoshimoto/libk4w2#9]
progmaster@Microsoft:~/Kinect/libk4w2/build$ make
Scanning dependencies of target k4w2
[  5%] Building C object src/CMakeFiles/k4w2.dir/libk4w2.c.o
[ 11%] Building C object src/CMakeFiles/k4w2.dir/misc.c.o
[ 16%] Building C object src/CMakeFiles/k4w2.dir/driver.c.o
[ 22%] Building C object src/CMakeFiles/k4w2.dir/driver_v4l2.c.o
[ 27%] Building C object src/CMakeFiles/k4w2.dir/driver_libusb/driver_libusb.c.o
[ 33%] Building C object src/CMakeFiles/k4w2.dir/driver_libusb/usb_dev.c.o
[ 38%] Building C object src/CMakeFiles/k4w2.dir/driver_libusb/usb_stream.c.o
[ 44%] Building C object src/CMakeFiles/k4w2.dir/decoder_cpu/color_cpu.c.o
[ 50%] Building C object src/CMakeFiles/k4w2.dir/decoder_cpu/depth_cpu.c.o
[ 55%] Building C object src/CMakeFiles/k4w2.dir/registration.c.o
[ 61%] Building C object src/CMakeFiles/k4w2.dir/ir_table.c.o
[ 66%] Building CXX object src/CMakeFiles/k4w2.dir/decoder_cl/depth_cl.cpp.o
[ 72%] Building C object src/CMakeFiles/k4w2.dir/decoder_cuda/color_cuda.c.o
[ 77%] Building C object src/CMakeFiles/k4w2.dir/decoder.c.o
Linking CXX shared library ../lib/libk4w2.so
[ 77%] Built target k4w2
Scanning dependencies of target liveview
[ 83%] Building CXX object examples/CMakeFiles/liveview.dir/liveview.cpp.o
Linking CXX executable ../bin/liveview
../lib/libk4w2.so.0.0.0: undefined reference to `clCreateFromGLTexture'
../lib/libk4w2.so.0.0.0: undefined reference to `clCreateImage'
../lib/libk4w2.so.0.0.0: undefined reference to `clRetainDevice'
../lib/libk4w2.so.0.0.0: undefined reference to `clReleaseDevice'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/liveview] Error 1
make[1]: *** [examples/CMakeFiles/liveview.dir/all] Error 2
make: *** [all] Error 2

**Comment by ProgmasterX** [comment]
I didn't have CUDA drivers installed. Now another error.

**Comment by yoshimoto** [comment]
I've improved CMakeList.txt to avoid posibel issues like this.
Thank you
